### ISSUE TITLE
[BUG] The requested module 'noblox.js' does not provide an export named 'getProductInfo'

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [noblox/noblox.js#670]
## Before posting a bug, be sure that someone else has not posted it already and it is an actual bug with noblox.js and not other frameworks like discord.js

**Describe the bug**
```
SyntaxError: The requested module 'noblox.js' does not provide an export named 'getProductInfo'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**To Reproduce**
```
import { getProductInfo } from 'noblox.js';
```

**Expected behavior**
It should not error.

**Screenshots**
N/A

**Additional context**
If you would like to see the implementation or how I did things with ``noblox.js``, [see here](https://github.com/RealEthanPlayzDev/Meteorium/blob/typescript-rewrite/src/commands/Info/RbxAPI.ts), however it looks like this only happens when importing it.

**Comment by suufi** [comment]
Has been fixed. Please update to v4.14.0.

**Comment by RealEthanPlayzDev** [comment]
@suufi 
> Has been fixed. Please update to v4.14.0.
Hi, sorry for bothering, however I still get the error:
```
import { getProductInfo } from 'noblox.js';
         ^

SyntaxError: The requested module 'noblox.js' does not provide an export named 'getProductInfo'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
 ```
 
 An alternative is to import everything in the module as something and then referencing it like below:
 ```
 import * as nobloxjs from 'noblox.js';
 await nobloxjs.getProductInfo(assetId);
 ```
